// Auto-generated file - do not edit manually
// Generated by convert_board_states.py

#ifndef BOARD_STATES_HH
#define BOARD_STATES_HH

namespace Student {

const int NUM_BOARD_STATES = 18;

const bool BOARD_STATES[NUM_BOARD_STATES][8][8] = {
    // Board_State_0.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_1.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, true, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_2.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, false, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, true, false, false, false, false},
        {false, false, true, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_3.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, false, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, true, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_4.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, false, false, true, true, true, true},
        {false, false, true, false, false, false, false, false},
        {false, false, false, true, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_5.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, false, false, true, true, true, true},
        {false, false, true, false, false, false, false, false},
        {false, false, false, true, false, false, false, false},
        {false, true, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, false, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_6.txt
    {
        {true, false, true, true, true, true, true, true},
        {true, true, false, false, true, true, true, true},
        {true, false, true, false, false, false, false, false},
        {false, false, false, true, false, false, false, false},
        {false, true, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, false, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_7.txt
    {
        {true, false, true, true, true, true, true, true},
        {true, true, false, false, true, true, true, true},
        {true, false, true, false, false, false, false, false},
        {false, false, false, true, false, false, false, false},
        {true, true, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_8.txt
    {
        {true, false, true, true, true, true, true, true},
        {true, true, false, false, true, true, true, true},
        {false, false, true, false, false, false, false, false},
        {false, false, false, true, false, false, false, false},
        {true, true, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_9.txt
    {
        {true, false, true, true, true, true, true, true},
        {true, true, false, false, true, true, true, true},
        {false, false, true, false, false, false, false, false},
        {true, false, false, true, false, false, false, false},
        {false, true, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_10.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_11.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_12.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_13.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_14.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_15.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_16.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    },
    // Board_State_17.txt
    {
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {false, false, false, false, false, false, false, false},
        {true, true, true, true, true, true, true, true},
        {true, true, true, true, true, true, true, true}
    }
};

} // namespace Student

#endif // BOARD_STATES_HH
