#!/usr/bin/env python3
import os
import re
import sys

def parse_board_state_file(filepath):
    """Parse a board state file and return 8x8 bool array of occupied positions."""
    occupied = [[False for _ in range(8)] for _ in range(8)]

    try:
        with open(filepath, 'r') as f:
            lines = f.readlines()

        # Parse lines 3-10 (indices 2-9) which contain rows 0-7
        for i in range(8):
            if i + 2 >= len(lines):
                print(f"Warning: {filepath} has insufficient lines", file=sys.stderr)
                return None

            line = lines[i + 2]  # Skip header lines

            # Find the content between | |
            match = re.search(r'\d\|(.*)\|', line)
            if not match:
                print(f"Warning: Could not parse line {i+2} in {filepath}", file=sys.stderr)
                continue

            content = match.group(1)

            # Columns 2-9 in display are positions 4-19 in content string (0-indexed)
            # Each column takes 2 characters in the display
            # Column layout: "    " (4 spaces for cols 0-1) + content for cols 2-9 + "    " (4 spaces for cols A-B)
            for col in range(8):
                # Column 2 starts at position 4, each column is 2 chars wide
                char_pos = 4 + (col * 2)
                if char_pos < len(content):
                    if content[char_pos] == 'x':
                        occupied[i][col] = True

        return occupied

    except Exception as e:
        print(f"Error parsing {filepath}: {e}", file=sys.stderr)
        return None

def find_board_state_files(board_states_dir):
    """Find all Board_State_#.txt files and return sorted list."""
    files = []

    if not os.path.exists(board_states_dir):
        print(f"Error: Directory {board_states_dir} does not exist", file=sys.stderr)
        return files

    for filename in os.listdir(board_states_dir):
        match = re.match(r'Board_State_(\d+)\.txt', filename)
        if match:
            number = int(match.group(1))
            filepath = os.path.join(board_states_dir, filename)
            files.append((number, filepath))

    # Sort by state number
    files.sort(key=lambda x: x[0])
    return files

def generate_header_file(board_states, output_path):
    """Generate C++ header file with board state data."""

    with open(output_path, 'w') as f:
        f.write("// Auto-generated file - do not edit manually\n")
        f.write("// Generated by convert_board_states.py\n\n")
        f.write("#ifndef BOARD_STATES_HH\n")
        f.write("#define BOARD_STATES_HH\n\n")
        f.write("namespace Student {\n\n")

        # Write number of states
        f.write(f"const int NUM_BOARD_STATES = {len(board_states)};\n\n")

        # Write board states array
        f.write("const bool BOARD_STATES[NUM_BOARD_STATES][8][8] = {\n")

        for state_idx, (state_num, occupied) in enumerate(board_states):
            f.write(f"    // Board_State_{state_num}.txt\n")
            f.write("    {\n")
            for row in range(8):
                f.write("        {")
                for col in range(8):
                    f.write("true" if occupied[row][col] else "false")
                    if col < 7:
                        f.write(", ")
                f.write("}")
                if row < 7:
                    f.write(",")
                f.write("\n")
            f.write("    }")
            if state_idx < len(board_states) - 1:
                f.write(",")
            f.write("\n")

        f.write("};\n\n")
        f.write("} // namespace Student\n\n")
        f.write("#endif // BOARD_STATES_HH\n")

def main():
    # Determine paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    board_states_dir = os.path.join(project_root, "Board_States")
    output_path = os.path.join(script_dir, "BoardStates.hh")

    print(f"Scanning for board state files in: {board_states_dir}")

    # Find all board state files
    state_files = find_board_state_files(board_states_dir)

    if not state_files:
        print("Warning: No Board_State_#.txt files found", file=sys.stderr)
        # Generate empty header
        with open(output_path, 'w') as f:
            f.write("// Auto-generated file - no board states found\n")
            f.write("#ifndef BOARD_STATES_HH\n")
            f.write("#define BOARD_STATES_HH\n")
            f.write("namespace Student {\n")
            f.write("const int NUM_BOARD_STATES = 0;\n")
            f.write("const bool BOARD_STATES[1][8][8] = {{}};\n")
            f.write("}\n")
            f.write("#endif\n")
        return 0

    print(f"Found {len(state_files)} board state files")

    # Parse all files
    board_states = []
    for state_num, filepath in state_files:
        occupied = parse_board_state_file(filepath)
        if occupied is not None:
            board_states.append((state_num, occupied))
            print(f"  Parsed Board_State_{state_num}.txt")
        else:
            print(f"  Failed to parse Board_State_{state_num}.txt", file=sys.stderr)

    if not board_states:
        print("Error: No valid board states parsed", file=sys.stderr)
        return 1

    # Generate header file
    generate_header_file(board_states, output_path)
    print(f"Generated {output_path} with {len(board_states)} states")

    return 0

if __name__ == "__main__":
    sys.exit(main())
