#define SLEEP_PIN GPIO_NUM_36
#define EN_PIN GPIO_NUM_35
#define MODE0_PIN GPIO_NUM_0
#define MODE1_PIN GPIO_NUM_45
#define DIR1_PIN GPIO_NUM_13
#define MODE2_PIN GPIO_NUM_47
#define STEP1_PIN GPIO_NUM_12
#define HFS_PIN GPIO_NUM_14
#define DIR2_PIN GPIO_NUM_48
#define STEP2_PIN GPIO_NUM_21

#define MAGNET_PIN GPIO_NUM_38

